using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Platform.Storage;
using CoreKeeperSkinTool.Editing;
using CoreKeeperSkinTool.Gui.Editing;
using CoreKeeperSkinTool.Gui.Localization;
using CoreKeeperSkinTool.Install;
using CoreKeeperSkinTool.Gui.ViewModels;

namespace CoreKeeperSkinTool.Gui.Views;

public partial class MainWindow : Window
{
    /// <summary>Extensions accepted for loading, matching what SkiaSharp can decode.</summary>
    private static readonly string[] ImageExtensions =
        [".png", ".jpg", ".jpeg", ".bmp", ".gif", ".webp"];

    public MainWindow()
    {
        // InitializeComponent is generated by Avalonia.
        // Defining it by hand skips the field assignment for x:Name controls, leaving the
        // button references null. Do not define it.
        InitializeComponent();
        DataContext = new MainViewModel();

        OpenButton.Click += OnOpenClicked;
        SaveButton.Click += OnSaveClicked;
        InstallButton.Click += OnInstallClicked;
        UninstallButton.Click += OnRemoveFromCharactersClicked;
        // A character created in the game while this window is open has to show up. Switching
        // back to the window is the moment that always happens, and the scan is skipped unless
        // the save folder actually changed.
        Activated += (_, _) => Model.RefreshCharactersIfChanged();
        // The same moment for the game's log: starting the game and watching it refuse the mod
        // ends with switching back here. Read again only when the log has changed.
        Activated += (_, _) => Model.RefreshModLoadIfChanged();

        InstallModButton.Click += OnModButtonClicked;
        GamePathButton.Click += OnGamePathClicked;
        SelectAllCharactersButton.Click += (_, _) => Model.SelectAllCharacters(true);
        SelectNoCharactersButton.Click += (_, _) => Model.SelectAllCharacters(false);
        SideImageButton.Click += async (_, _) => await OnFacingClickedAsync(side: true);
        BackImageButton.Click += async (_, _) => await OnFacingClickedAsync(side: false);
        ClearSideImageButton.Click += async (_, _) => await Model.ClearSideImageAsync();
        ClearBackImageButton.Click += async (_, _) => await Model.ClearBackImageAsync();
        HelpButton.Click += OnHelpClicked;
        RegenerateButton.Click += OnRegenerateClicked;
        UndoButton.Click += (_, _) => Model.Undo();
        RedoButton.Click += (_, _) => Model.Redo();

        Canvas.PixelPointer += (_, e) => Model.HandlePixel(e.X, e.Y, e.IsStart, e.IsErase, e.IsInterpolated);
        Canvas.HoverChanged += (_, e) => Model.UpdateCursorInfo(e.X, e.Y);
        Canvas.StrokeEnded += (_, _) => Model.EndStroke();
        Canvas.OtherButtonPressed += (_, _) => Model.CancelShapeInProgress();
        RandomButton.Click += (_, _) => Model.LoadRandomCharacter();
        RecolorButton.Click += (_, _) => Model.RecolourToSelectedPreset();

        // A file the size of a sheet that also paints outside the frames is almost certainly not
        // a sheet. Asked rather than guessed: guessing wrong either way used to leave no way back.
        Model.AskWhetherToOpenAsSheet = async () =>
        {
            ConfirmWindow dialog = new(
                Loc.Instance["confirm.openAsSheet"],
                "confirm.openAsSheetOk",
                cancelLabelKey: "confirm.openAsSheetConvert");

            return await dialog.ShowDialog<bool?>(this);
        };

        // The fetch button lives inside the character list, so it binds to a command rather than
        // being reached by name. The question about losing edits therefore has to travel the other
        // way: the view model asks, and the window is what can put a dialog on screen.
        Model.AskWhetherToDiscardEdits = () => ConfirmDiscardEditsAsync("confirm.fetch", "confirm.fetchOk");

        UpdateModButton.Click += (_, _) => Model.UpdateMod();

        AddHandler(DragDrop.DragOverEvent, OnDragOver);
        AddHandler(DragDrop.DropEvent, OnDrop);
        AddHandler(KeyDownEvent, OnKeyDown, RoutingStrategies.Tunnel);

        Closing += OnClosing;
    }

    private MainViewModel Model => (MainViewModel)DataContext!;

    /// <summary>Set once the user has confirmed closing, so the second Close goes through.</summary>
    private bool _closeConfirmed;

    /// <summary>
    /// Set while the closing question is on screen.
    ///
    /// Clicking the title bar's X twice cannot get past it - the dialog disables its owner - but
    /// a Close() from code can, and two of those put two identical confirmations on screen at
    /// once. Cancelling and returning leaves the one already asked to do the answering.
    /// </summary>
    private bool _askingToClose;

    /// <summary>
    /// Asks before dropping unsaved pixel work on the way out. Nothing is auto-saved, so the
    /// drawing is gone for good, and an edit that has not been applied to a character exists
    /// nowhere but in this window.
    ///
    /// Closing cannot be awaited, so the close is cancelled, the question asked, and Close()
    /// called again once the answer is in.
    ///
    /// Only when the user closes this window. Windows raises the same event while shutting down
    /// or signing out, and cancelling that to put up a modal - one that can sit behind other
    /// windows where nobody sees it - stalls the shutdown for a question the user never asked
    /// for.
    ///
    /// The reason is all that is checked. A programmatic close is deliberately still asked
    /// about: the only one this program makes is the second Close below, which _closeConfirmed
    /// already lets through, and skipping every programmatic close would silently drop the
    /// question the day something like a Quit menu item is added.
    /// </summary>
    private async void OnClosing(object? sender, WindowClosingEventArgs e)
    {
        if (e.CloseReason != WindowCloseReason.WindowClosing)
        {
            return;
        }

        if (_closeConfirmed || !Model.WouldDiscardEdits)
        {
            return;
        }

        e.Cancel = true;

        if (_askingToClose)
        {
            return;
        }

        _askingToClose = true;
        try
        {
            ConfirmWindow dialog = new(Loc.Instance["confirm.exit"], "confirm.exitOk");
            if (await dialog.ShowDialog<bool?>(this) == true)
            {
                _closeConfirmed = true;
                Close();
            }
        }
        finally
        {
            _askingToClose = false;
        }
    }

    // ------------------------------------------------------------ Keyboard

    private void OnKeyDown(object? sender, KeyEventArgs e)
    {
        // Do nothing while a text box has focus, so undo is not stolen from typing
        if (FocusManager?.GetFocusedElement() is TextBox)
        {
            return;
        }

        bool control = e.KeyModifiers.HasFlag(KeyModifiers.Control);

        // Undo is the only shortcut that takes a modifier. Letting the plain-letter ones through
        // on Ctrl or Alt meant Ctrl+B silently changed tool and swallowed the key on the way.
        if (e.Key is not (Key.Z or Key.Y)
            && (control || e.KeyModifiers.HasFlag(KeyModifiers.Alt)))
        {
            return;
        }

        // Escape while a line or rectangle is being dragged calls it off: the preview goes, and
        // letting go writes nothing. There was no other way to - the canvas keeps a stroke to the
        // button that began it - so a shape seen in the wrong place could only be written and
        // then undone, over every frame by default.
        if (e.Key == Key.Escape && Canvas.IsPainting && Model.CancelShapeInProgress())
        {
            e.Handled = true;
            return;
        }

        // Nothing else is accepted while the button is down.
        //
        // Switching tool mid-stroke changes what a half-drawn shape will become, and the shape
        // keeps the tool it started with, so the change would be invisible until the stroke ended.
        // Undo used to be let through, on the reasoning that it takes a modifier and so could not
        // be a stray keypress. It could still be a stray moment: undoing part-way through a drag
        // took back the step before it and then let the rest of the same drag record a step of its
        // own, so one drag became two and the half already drawn was gone. Ignored, the reflex
        // costs nothing - releasing the button and undoing then takes back the whole stroke, which
        // is what was wanted.
        if (Canvas.IsPainting)
        {
            return;
        }

        switch (e.Key)
        {
            case Key.Z when control && e.KeyModifiers.HasFlag(KeyModifiers.Shift):
            case Key.Y when control:
                Model.Redo();
                e.Handled = true;
                break;

            case Key.Z when control:
                Model.Undo();
                e.Handled = true;
                break;

            case Key.B:
                Model.Tool = EditorTool.Pen;
                e.Handled = true;
                break;

            case Key.E:
                Model.Tool = EditorTool.Eraser;
                e.Handled = true;
                break;

            case Key.I:
                Model.Tool = EditorTool.Picker;
                e.Handled = true;
                break;

            case Key.G:
                Model.Tool = EditorTool.Bucket;
                e.Handled = true;
                break;

            case Key.L:
                Model.Tool = EditorTool.Line;
                e.Handled = true;
                break;

            case Key.U:
                Model.Tool = EditorTool.Rectangle;
                e.Handled = true;
                break;

            case Key.R:
                Model.Tool = EditorTool.ColourReplace;
                e.Handled = true;
                break;

            case Key.M:
                Model.MirrorDrawing = !Model.MirrorDrawing;
                e.Handled = true;
                break;
        }
    }

    // ------------------------------------------------------------ Drag and drop

    private static void OnDragOver(object? sender, DragEventArgs e)
    {
        // Show through the cursor that only image files are accepted
        e.DragEffects = TryGetImagePath(e) is not null ? DragDropEffects.Copy : DragDropEffects.None;
        e.Handled = true;
    }

    private async void OnDrop(object? sender, DragEventArgs e)
    {
        string? path = TryGetImagePath(e);
        if (path is not null && await ConfirmDiscardEditsAsync())
        {
            await Model.LoadImageAsync(path);
        }

        e.Handled = true;
    }

    /// <summary>
    /// Asks before hand-drawn work is thrown away, and answers true when there is nothing to
    /// lose. Loading an image rebuilds the document from scratch, so the undo history goes with
    /// it and Ctrl+Z cannot bring the drawing back.
    ///
    /// The drop target is the whole window, so this also catches a file let go over it by
    /// accident - which was the one route into losing an edit that asked nothing and offered no
    /// way back, while rebuilding from the settings confirms and choosing a preset is undoable.
    ///
    /// The wording is a parameter because fetching from the game loses edits the same way but is
    /// not a file being loaded. Asking about the wrong action reads as a mis-click, and the
    /// natural answer to that is cancel - which made the fetch button look like it did nothing.
    /// </summary>
    private async Task<bool> ConfirmDiscardEditsAsync(
        string messageKey = "confirm.loadImage",
        string okLabelKey = "confirm.loadImageOk")
    {
        if (!Model.WouldDiscardEdits)
        {
            return true;
        }

        ConfirmWindow dialog = new(Loc.Instance[messageKey], okLabelKey);
        return await dialog.ShowDialog<bool?>(this) == true;
    }

    private static string? TryGetImagePath(DragEventArgs e)
    {
        // Several files at once is refused rather than quietly reduced to one. Which one
        // TryGetFile hands back follows the shell's ordering of the selection, not the item under
        // the cursor, so the picture that appeared could be one the user was not pointing at and
        // nothing said the others had been thrown away. Refusing also makes the drag cursor say
        // no, which is what the file picker says too with AllowMultiple = false.
        //
        // Asked as "more than one" so that a platform which offers no file list at all behaves
        // exactly as it did before, rather than losing drag and drop altogether.
        if (e.DataTransfer?.TryGetFiles() is { Length: > 1 })
        {
            return null;
        }

        // Avalonia 12 moved drag data access from IDataObject to IDataTransfer
        IStorageItem? item = e.DataTransfer?.TryGetFile();
        string? path = item?.TryGetLocalPath();
        if (path is null)
        {
            return null;
        }

        string extension = Path.GetExtension(path).ToLowerInvariant();
        return ImageExtensions.Contains(extension) ? path : null;
    }

    // ------------------------------------------------------------ Buttons

    /// <summary>
    /// Lets the user point at the game folder themselves.
    ///
    /// Detection follows Steam's own library records and copes with any drive, but this is the
    /// way out if it ever fails: an unreadable registry, a library Steam has forgotten, or a
    /// copy of the game moved by hand.
    /// </summary>
    private async void OnGamePathClicked(object? sender, RoutedEventArgs e)
    {
        try
        {
            // Offer to go back to automatic detection first, so a wrong choice is not permanent
            if (MainViewModel.HasManualGamePath)
            {
                // The other button is named for what it leads to. Declining detection goes on to
                // the folder picker below, the one way from one chosen folder to another, and a
                // button saying "やめる" then opened the picker anyway.
                ConfirmWindow reset = new(
                    Loc.Instance["confirm.gamePathReset"], "confirm.gamePathResetOk",
                    cancelLabelKey: "confirm.gamePathResetPick");

                bool? answer = await reset.ShowDialog<bool?>(this);

                // Escape or the close button: no answer, and both buttons are an action, so
                // neither is taken. It went on to the folder picker, as the second button does.
                if (answer is null)
                {
                    return;
                }

                if (answer == true)
                {
                    Model.SetGamePath(null);
                    return;
                }
            }

            var folders = await StorageProvider.OpenFolderPickerAsync(new FolderPickerOpenOptions
            {
                Title = Loc.Instance["dialog.gamePathTitle"],
                AllowMultiple = false,
            });

            string? path = folders.FirstOrDefault()?.TryGetLocalPath();
            if (path is not null)
            {
                Model.SetGamePath(path);
            }
        }
        catch (Exception ex)
        {
            Model.SetStatus("status.pickFailed", ex);
        }
    }

    /// <summary>
    /// Picks a picture for one of the optional facings.
    ///
    /// No question about discarding edits, unlike opening a front picture: this replaces the art
    /// in one direction's frames and leaves the canvas as it is.
    /// </summary>
    private async Task OnFacingClickedAsync(bool side)
    {
        try
        {
            var files = await StorageProvider.OpenFilePickerAsync(new FilePickerOpenOptions
            {
                Title = Loc.Instance[side ? "views.side" : "views.back"],
                AllowMultiple = false,
                FileTypeFilter =
                [
                    new FilePickerFileType(Loc.Instance["dialog.imageFilter"])
                    {
                        Patterns = [.. ImageExtensions.Select(x => "*" + x)],
                    },
                ],
            });

            if (files.FirstOrDefault()?.TryGetLocalPath() is { } path)
            {
                await (side ? Model.LoadSideImageAsync(path) : Model.LoadBackImageAsync(path));
            }
        }
        catch (Exception ex)
        {
            Model.SetStatus("status.pickFailed", ex);
        }
    }

    private async void OnOpenClicked(object? sender, RoutedEventArgs e)
    {
        try
        {
            var files = await StorageProvider.OpenFilePickerAsync(new FilePickerOpenOptions
            {
                Title = Loc.Instance["dialog.openTitle"],
                AllowMultiple = false,
                FileTypeFilter =
                [
                    new FilePickerFileType(Loc.Instance["dialog.imageFilter"])
                    {
                        Patterns = [.. ImageExtensions.Select(x => "*" + x)],
                    },
                ],
            });

            string? path = files.FirstOrDefault()?.TryGetLocalPath();
            if (path is not null && await ConfirmDiscardEditsAsync())
            {
                await Model.LoadImageAsync(path);
            }
        }
        catch (Exception ex)
        {
            Model.SetStatus("status.pickFailed", ex);
        }
    }

    private async void OnSaveClicked(object? sender, RoutedEventArgs e)
    {
        try
        {
            IStorageFile? file = await StorageProvider.SaveFilePickerAsync(new FilePickerSaveOptions
            {
                Title = Loc.Instance["dialog.saveTitle"],
                SuggestedFileName = "Skin.png",
                DefaultExtension = "png",
                FileTypeChoices = [new FilePickerFileType("PNG") { Patterns = ["*.png"] }],
            });

            string? path = file?.TryGetLocalPath();
            if (path is not null)
            {
                // After any conversion still on its way, so what is written is what is on screen
                await Model.SaveWhenSettledAsync(path);
            }
        }
        catch (Exception ex)
        {
            Model.SetStatus("status.saveFailed", ex);
        }
    }

    private async void OnInstallClicked(object? sender, RoutedEventArgs e)
    {
        // After any conversion or load still on its way: pressed just after a setting changed,
        // it put the previous picture into the game while the screen went on to the new one
        try
        {
            await Model.InstallToGameWhenSettledAsync();
        }
        catch (Exception ex)
        {
            Model.SetStatus("status.installFailed", ex);
        }
    }

    /// <summary>
    /// Opens the help window.
    ///
    /// Building it reads the embedded help text, which throws when the distribution is
    /// incomplete. Every other action in this window reports such a failure in the status
    /// line; without this handler the same failure would instead end the application and
    /// take any unsaved pixel edits with it.
    /// </summary>
    private async void OnHelpClicked(object? sender, RoutedEventArgs e)
    {
        try
        {
            await new HelpWindow().ShowDialog(this);
        }
        catch (ToolException ex)
        {
            Model.SetStatus(ex);
        }
        catch (Exception ex)
        {
            Model.SetStatus("status.helpFailed", ex);
        }
    }

    /// <summary>
    /// Takes the replaced appearance off the ticked characters, leaving the mod installed.
    ///
    /// Confirmed first, and only the characters that actually have one are listed: ticking a
    /// character that was never applied to does nothing, and saying otherwise would be a lie.
    /// </summary>
    private async void OnRemoveFromCharactersClicked(object? sender, RoutedEventArgs e)
    {
        IReadOnlyList<string> affected = Model.CharactersWithSkinToRemove();

        // Captured alongside the names shown, and handed back after the answer. Closing this
        // dialog activates the window, which rescans the save folder and rebuilds the rows
        // before the line below runs, so reading the selection again could act on a different
        // set from the one the user was asked about.
        IReadOnlyList<string> confirmed = Model.GuidsWithSkinToRemove();

        if (affected.Count == 0)
        {
            Model.SetStatus("status.removeCharactersNothing");
            return;
        }

        ConfirmWindow dialog = new(
            Loc.Instance.Format("confirm.removeCharacters", affected.Count),
            "confirm.removeCharactersOk",
            string.Join(Environment.NewLine, affected));

        if (await dialog.ShowDialog<bool?>(this) == true)
        {
            // After any conversion on its way, so its summary does not write over the report
            await Model.RemoveFromCharactersWhenSettledAsync(confirmed);
        }
    }

    /// <summary>
    /// The one button in the top bar: it puts the mod into the game, or takes it back out.
    /// </summary>
    private async void OnModButtonClicked(object? sender, RoutedEventArgs e)
    {
        if (!Model.IsModInstalled)
        {
            Model.InstallMod();
            return;
        }

        await RemoveModAsync();
    }

    /// <summary>
    /// Removes the mod and everything it applied.
    /// Lists exactly what will be removed and from where before doing it.
    /// </summary>
    private async Task RemoveModAsync()
    {
        RemovalPlan? plan = Model.PlanRemoval();

        // Null means the scan failed and PlanRemoval already explained why. Saying
        // "nothing to remove" here would overwrite that with the opposite of the truth.
        if (plan is null)
        {
            return;
        }

        if (plan.IsEmpty)
        {
            // Nothing to remove means the mod went away outside this window while the bar still
            // said it was installed. Re-read first and report after, as ExecuteRemoval does after a
            // partial removal, so the button turns back into "Install mod" and a failed character
            // scan cannot overwrite the report.
            Model.RefreshEnvironment();
            Model.SetStatus("status.uninstallNothing");
            return;
        }

        string detail = string.Join(
            Environment.NewLine,
            plan.Targets.Select(t =>
            {
                string kind = Loc.Instance[
                    t.Kind == RemovalKind.ModInstall ? "uninstall.kindMod" : "uninstall.kindConfig"];
                string count = t.IsFileCountUnknown
                    ? Loc.Instance["uninstall.fileCountUnknown"]
                    : Loc.Instance.Format("uninstall.fileCount", t.FileCount);
                return $"[{kind}] {t.Path}{Environment.NewLine}    {count}";
            }));

        // When a count is unknown the total is only a lower bound, so it must not be
        // presented as an exact figure right before an irreversible delete.
        string message = plan.HasUnknownFileCount
            ? Loc.Instance.Format("confirm.uninstallUnknown", plan.Targets.Count)
            : Loc.Instance.Format("confirm.uninstall", plan.Targets.Count, plan.TotalFiles);

        ConfirmWindow dialog = new(message, "confirm.uninstallOk", detail);

        if (await dialog.ShowDialog<bool?>(this) == true)
        {
            Model.ExecuteRemoval(plan);
        }
    }

    private async void OnRegenerateClicked(object? sender, RoutedEventArgs e)
    {
        // Confirm here so that hand-drawn edits are never discarded silently
        if (Model.WouldDiscardEdits)
        {
            ConfirmWindow dialog = new(Loc.Instance["confirm.regenerate"], "confirm.ok");
            if (await dialog.ShowDialog<bool?>(this) != true)
            {
                return;
            }
        }

        await Model.RegenerateAsync();
    }
}
